databricks_demo:
  outputs:
    dev:
      catalog: kb_dbt_demo
      schema: databricks_demo
      host: e2-demo-field-eng.cloud.databricks.com
      http_path: /sql/1.0/warehouses/ead10bf07050390f
      keepalives_idle: 60
      threads: 1
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      type: databricks
  target: dev